# Generated by Django 4.2.30 on 2026-09-14 07:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('event', 'Event Management'), ('marketing', 'Marketing & Communications'), ('creative', 'Creative Production'), ('web', 'Web Development')], default='event', max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('project_url', models.URLField(blank=True, default='')),
            ],
        ),
    ]
