# Generated by Django 4.2.30 on 2026-09-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
