# Generated by Django 4.2.30 on 2026-09-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_starred_by_alter_project_project_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
